import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Sidebar from "./Shared/Sidebar/Sidebar";
import Navigation from "./Shared/Navigation/Navigation";
import Footer from "./Shared/Footer/Footer";


export const metadata = {
  title: "Repwoop POS Software",
  description: "Generated by create Repwoop",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      
      <body
        className="font">
       <div className="h-screen flex ">
      {/* LEFT w-[14%] */}
      <div className="w-[8%] md:w-[8%] lg:w-[16%] xl:w-[14%] p-0">
        <Sidebar />
      </div>
      {/* RIGHT */}
      <div className="w-[90%] md:w-[95%] lg:w-[84%] xl:w-[92%] bg-[#F7F8FA] overflow-scroll flex flex-col">
        <Navigation />
        {children}
        <Footer/>
      </div>
    </div>
      </body>
    </html>
  );
}
