import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Sidebar from "./Shared/Sidebar/Sidebar";
import Navigation from "./Shared/Navigation/Navigation";
import Footer from "./Shared/Footer/Footer";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Repwoop POS Software",
  description: "Generated by create Repwoop",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
       <div className="h-screen flex ">
      {/* LEFT */}
      <div className="w-[14%] md:w-[8%] lg:w-[16%] xl:w-[14%] p-0">
        <Sidebar />
      </div>
      {/* RIGHT */}
      <div className="w-[86%] md:w-[92%] lg:w-[84%] xl:w-[92%] bg-[#F7F8FA] overflow-scroll flex flex-col">
        <Navigation />
        {children}
        <Footer/>
      </div>
    </div>
      </body>
    </html>
  );
}
